export const Types = {
    SET_POKEMON: "SET_POKEMON",
    REMOVE_POKEMON: "REMOVE_POKEMON",

    SET_POKEMON_BY_NAME: "SET_POKEMON_BY_NAME",
    REMOVE_POKEMON_BY_NAME: "REMOVE_POKEMON_BY_NAME",

    GET_SPECIES: "GET_SPECIES",
    REMOVE_SPECIES: "REMOVE_SPECIES",

    GET_EVOLUTION: "GET_EVOLUTION",
}